name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install qemu
        run: >
          apt-get install -yq
          qemu-system-i386
          qemu-utils

      - name: Install test requirements
        run: pip install -U -r requirements.tests.txt

      - name: Install package
        run: pip install -e .

      - name: Lint
        run: pylint librouteros

      - name: Format
        run: >
          yapf -dr
          librouteros
          tests

      - name: Download routeros images
        run: |
          wget --quiet netng.pl/routeros_test_images/routeros_6.33.3.qcow2 -O images/routeros_6.33.3.qcow2
          wget --quiet netng.pl/routeros_test_images/routeros_6.44.5.qcow2 -O images/routeros_6.44.5.qcow2

      - name: Unit tests
        run: pytest tests/unit

      - name: Integration tests
        run: pytest -n auto tests/integration
